### ISSUE TITLE
crash in Connection.js

### ISSUE THREAD

**Issue by phil-mitchell** [SAP/node-hdb#105]
11/1/17 4:08:22.214 PM [APP/266-3] ERR    node_modules/hdb/lib/protocol/Connection.js:280
11/1/17 4:08:22.218 PM [APP/266-3] ERR      state.messageType = message.type;
11/1/17 4:08:22.218 PM [APP/266-3] ERR                        ^
11/1/17 4:08:22.218 PM [APP/266-3] ERR
11/1/17 4:08:22.218 PM [APP/266-3] ERR    TypeError: Cannot set property 'messageType' of undefined
11/1/17 4:08:22.219 PM [APP/266-3] ERR        at Connection.send (/hana/shared/H4C/xs/app_working/mo-a4aa5acbc/executionroot/53342865-82d1-4170-b58a-dc75943d0bea/app/node_modules/hdb/lib/protocol/Connection.js:280:21)
11/1/17 4:08:22.219 PM [APP/266-3] ERR        at Connection.fetchDbConnectInfo (/hana/shared/H4C/xs/app_working/mo-a4aa5acbc/executionroot/53342865-82d1-4170-b58a-dc75943d0bea/app/node_modules/hdb/lib/protocol/Connection.js:534:8)
11/1/17 4:08:22.219 PM [APP/266-3] ERR        at /hana/shared/H4C/xs/app_working/mo-a4aa5acbc/executionroot/53342865-82d1-4170-b58a-dc75943d0bea/app/node_modules/hdb/lib/protocol/ConnectionManager.js:91:10
11/1/17 4:08:22.219 PM [APP/266-3] ERR        at Socket.ondata (/hana/shared/H4C/xs/app_working/mo-a4aa5acbc/executionroot/53342865-82d1-4170-b58a-dc75943d0bea/app/node_modules/hdb/lib/protocol/Connection.js:187:5)
11/1/17 4:08:22.219 PM [APP/266-3] ERR        at emitOne (events.js:96:13)
11/1/17 4:08:22.219 PM [APP/266-3] ERR        at Socket.emit (events.js:188:7)
11/1/17 4:08:22.219 PM [APP/266-3] ERR        at readableAddChunk (_stream_readable.js:176:18)
11/1/17 4:08:22.219 PM [APP/266-3] ERR        at Socket.Readable.push (_stream_readable.js:134:10)
11/1/17 4:08:22.219 PM [APP/266-3] ERR        at TCP.onread (net.js:547:20)

**Comment by alexpenev-s** [comment]
Hi, Could you please provide a reproduction scenario?

**Comment by phil-mitchell** [comment]
Not particularly.  We saw this once in a timing-dependent scenario.  However, it's pretty obvious what the problem is.

**Comment by phil-mitchell** [comment]
When will a release be created with this fix?

**Comment by alexpenev-s** [comment]
The latest release is 0.15; it was released about a week ago and it contains the fix.

**Comment by phil-mitchell** [comment]
Thanks.  I did not see a v0.15.0 tag in github, so I was not aware of the new release.

**Comment by itramana** [comment]
We see a issue with following stack. We are running a version 0.13.0. Could you check if the following stack might be due to same issue.

TypeError: Cannot set property 'messageType' of undefined
4/6/20 1:14:28.619 AM [APP/2-0] ERR       at Connection.send (/app/node_modules/hdb/lib/protocol/Connection.js:280:21)
4/6/20 1:14:28.619 AM [APP/2-0] ERR       at send (/app/node_modules/hdb/lib/protocol/ExecuteTask.js:189:21)
4/6/20 1:14:28.619 AM [APP/2-0] ERR       at next (/app/node_modules/hdb/lib/protocol/ExecuteTask.js:157:14)
4/6/20 1:14:28.619 AM [APP/2-0] ERR       at handleParameters (app/node_modules/hdb/lib/protocol/ExecuteTask.js:152:5)
4/6/20 1:14:28.619 AM [APP/2-0] ERR       at Immediate.<anonymous> (/app/node_modules/hdb/lib/protocol/Writer.js:199:7)
4/6/20 1:14:28.619 AM [APP/2-0] ERR       at runCallback (timers.js:672:20)
4/6/20 1:14:28.619 AM [APP/2-0] ERR       at tryOnImmediate (timers.js:645:5)
4/6/20 1:14:28.619 AM [APP/2-0] ERR       at processImmediate [as _immediateCallback] (timers.js:617:5)
