### ISSUE TITLE
wrong port - connect callback not called

### ISSUE THREAD

**Issue by PSeitz** [SAP/node-hdb#26]
When I execute the example with a wrong but existing port, the connect callback ist not called.

**Comment by holgerkoser** [comment]
The callback is not called because no error occured. The initial handshake process sends data to the server. 
https://github.com/SAP/node-hdb/blob/master/lib/protocol/Connection.js#L162-L166
If this is successful and the server does not respond with any data nothing happens. It could be possible to add a timeout to the configuration, that aborts the connection in such a case.
